---
version: '3'
services:
  app:
    build: .
    image: "kathlon/kube-app-demo:v0.6.1"
    ports:
    - "8000:8000"
    - "9001:9001"
    volumes:
    - "./log-config.ini:/etc/config/log-config.ini"
